export const el = {
  taskForm: document.getElementById("taskForm"),
  taskId: document.getElementById("taskId"),
  taskTitle: document.getElementById("taskTitle"),
  taskPoints: document.getElementById("taskPoints"),
  saveTaskBtn: document.getElementById("saveTaskBtn"),
  cancelEditBtn: document.getElementById("cancelEditBtn"),
  taskImportFile: document.getElementById("taskImportFile"),
  reviewerForm: document.getElementById("reviewerForm"),
  reviewerName: document.getElementById("reviewerName"),
  reviewerList: document.getElementById("reviewerList"),
  autoAssignBtn: document.getElementById("autoAssignBtn"),
  clearReviewersBtn: document.getElementById("clearReviewersBtn"),
  taskList: document.getElementById("taskList"),
  downloadCsvBtn: document.getElementById("downloadCsvBtn"),
  clearTasksBtn: document.getElementById("clearTasksBtn"),
  stats: document.getElementById("stats"),
  confirmModal: document.getElementById("confirmModal"),
  confirmTitle: document.getElementById("confirmTitle"),
  confirmMessage: document.getElementById("confirmMessage"),
  confirmCancelBtn: document.getElementById("confirmCancelBtn"),
  confirmApproveBtn: document.getElementById("confirmApproveBtn"),
  toast: document.getElementById("toast"),
};
